<?php

/**
 * @file
 * Service_request module file.
 */

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function markaspot_validation_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() == 'node') {

    switch ($bundle) {
      case 'service_request':

        $address = $fields['field_address'];
        $address->addConstraint('ValidLocality', []);

        $latlon = $fields['field_geolocation'];
        $latlon->addConstraint('ValidLatLon');

      break;
    }
  }
}
